In [28]:
'''
Overview
this notebook parses all fighters' details and tale of the tape

scrape ufc fighters' details
includes first, last, nickname, url
from url scrape scrape fighter's tale of the tape, 
includes fighter, height, weight, reach, stance, dob
'''

"\nOverview\nthis notebook parses all fighters' details and tale of the tape\n\nscrape ufc fighters' details\nincludes first, last, nickname, url\nfrom url scrape scrape fighter's tale of the tape, \nincludes fighter, height, weight, reach, stance, dob\n"

In [29]:
# imports
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm_notebook

# import library
import scrape_ufc_stats_library as LIB
import importlib
importlib.reload(LIB)

# import configs
import yaml
config = yaml.safe_load(open('scrape_ufc_stats_config.yaml'))

# Parse Fighter Details
Includes:
<br>
First
<br>
Last
<br>
Nickname
<br>
URL

In [30]:
# generate list of urls for fighter details
list_of_alphabetical_urls = LIB.generate_alphabetical_urls()
print(list_of_alphabetical_urls)

['http://ufcstats.com/statistics/fighters?char=a&page=all', 'http://ufcstats.com/statistics/fighters?char=b&page=all', 'http://ufcstats.com/statistics/fighters?char=c&page=all', 'http://ufcstats.com/statistics/fighters?char=d&page=all', 'http://ufcstats.com/statistics/fighters?char=e&page=all', 'http://ufcstats.com/statistics/fighters?char=f&page=all', 'http://ufcstats.com/statistics/fighters?char=g&page=all', 'http://ufcstats.com/statistics/fighters?char=h&page=all', 'http://ufcstats.com/statistics/fighters?char=i&page=all', 'http://ufcstats.com/statistics/fighters?char=j&page=all', 'http://ufcstats.com/statistics/fighters?char=k&page=all', 'http://ufcstats.com/statistics/fighters?char=l&page=all', 'http://ufcstats.com/statistics/fighters?char=m&page=all', 'http://ufcstats.com/statistics/fighters?char=n&page=all', 'http://ufcstats.com/statistics/fighters?char=o&page=all', 'http://ufcstats.com/statistics/fighters?char=p&page=all', 'http://ufcstats.com/statistics/fighters?char=q&page=all', 'http://ufcstats.com/statistics/fighters?char=r&page=all', 'http://ufcstats.com/statistics/fighters?char=s&page=all', 'http://ufcstats.com/statistics/fighters?char=t&page=all', 'http://ufcstats.com/statistics/fighters?char=u&page=all', 'http://ufcstats.com/statistics/fighters?char=v&page=all', 'http://ufcstats.com/statistics/fighters?char=w&page=all', 'http://ufcstats.com/statistics/fighters?char=x&page=all', 'http://ufcstats.com/statistics/fighters?char=y&page=all', 'http://ufcstats.com/statistics/fighters?char=z&page=all']

In [31]:
# create empty dataframe to store all fighter details
all_fighter_details_df = pd.DataFrame()
print(all_fighter_details_df)

# loop through list of alphabetical urls
for url in tqdm_notebook(list_of_alphabetical_urls):
    # get soup
    print(url)
    soup = LIB.get_soup(url)
    print("hello this is after soup")
    # parse fighter details
    fighter_details_df = LIB.parse_fighter_details(soup, config['fighter_details_column_names'])
    print(fighter_details_df)
    # concat fighter_details_df to all_fighter_details_df
    all_fighter_details_df = pd.concat([all_fighter_details_df, fighter_details_df])
    print(all_fighter_details_df)

# show all fighter details
display(all_fighter_details_df)

# write to file
all_fighter_details_df.to_csv(config['fighter_details_file_name'], index=False)

Empty DataFrame
Columns: []
Index: []

  0%|          | 0/26 [00:00<?, ?it/s]

http://ufcstats.com/statistics/fighters?char=a&page=all
hello this is after soup
       FIRST        LAST         NICKNAME  \
0        Tom       Aaron
1      Danny      Abbadi     The Assassin
2    Nariman     Abbasov        Bayraktar
3      David      Abbott             Tank
4      Hamdy  Abdelwahab       The Hammer
..       ...         ...              ...
222      Abu     Azaitar  Captain Morocco
223   Ottman     Azaitar        Bulldozer
224     Luiz     Azeredo
225  Luciano     Azevedo
226   Hunter       Azure

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
222  http://ufcstats.com/fighter-details/46d0a888d8...
223  http://ufcstats.com/fighter-details/ee18ff4206...
224  http://ufcstats.com/fighter-details/063649e21b...
225  http://ufcstats.com/fighter-details/9bcfb40dbc...
226  http://ufcstats.com/fighter-details/2af2f2e26c...

[227 rows x 4 columns]
       FIRST        LAST         NICKNAME  \
0        Tom       Aaron
1      Danny      Abbadi     The Assassin
2    Nariman     Abbasov        Bayraktar
3      David      Abbott             Tank
4      Hamdy  Abdelwahab       The Hammer
..       ...         ...              ...
222      Abu     Azaitar  Captain Morocco
223   Ottman     Azaitar        Bulldozer
224     Luiz     Azeredo
225  Luciano     Azevedo
226   Hunter       Azure

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
222  http://ufcstats.com/fighter-details/46d0a888d8...
223  http://ufcstats.com/fighter-details/ee18ff4206...
224  http://ufcstats.com/fighter-details/063649e21b...
225  http://ufcstats.com/fighter-details/9bcfb40dbc...
226  http://ufcstats.com/fighter-details/2af2f2e26c...

[227 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=b&page=all
hello this is after soup
           FIRST       LAST            NICKNAME  \
0         Niklas  Backstrom
1           Seth  Baczynski  The Polish Pistola
2    Abdul Azeem  Badakhshi     The Afghan Lion
3           Ryan      Bader               Darth
4        Izabela    Badurek
..           ...        ...                 ...
311           JP       Buys        Young Savage
312       Dennis    Buzukja           The Great
313      Charles       Byrd        Kid Dynamite
314        Steve     Byrnes        The Sergeant
315      Michael     Byrnes

                                                   URL
0    http://ufcstats.com/fighter-details/39cc64bf0a...
1    http://ufcstats.com/fighter-details/fd5b6598a3...
2    http://ufcstats.com/fighter-details/968764372c...
3    http://ufcstats.com/fighter-details/c0ab242c40...
4    http://ufcstats.com/fighter-details/4fcf6e0c4e...
..                                                 ...
311  http://ufcstats.com/fighter-details/0b36224780...
312  http://ufcstats.com/fighter-details/c4d039123e...
313  http://ufcstats.com/fighter-details/76ee3d666c...
314  http://ufcstats.com/fighter-details/4361245697...
315  http://ufcstats.com/fighter-details/87f0b37f15...

[316 rows x 4 columns]
       FIRST        LAST      NICKNAME  \
0        Tom       Aaron
1      Danny      Abbadi  The Assassin
2    Nariman     Abbasov     Bayraktar
3      David      Abbott          Tank
4      Hamdy  Abdelwahab    The Hammer
..       ...         ...           ...
311       JP        Buys  Young Savage
312   Dennis     Buzukja     The Great
313  Charles        Byrd  Kid Dynamite
314    Steve      Byrnes  The Sergeant
315  Michael      Byrnes

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
311  http://ufcstats.com/fighter-details/0b36224780...
312  http://ufcstats.com/fighter-details/c4d039123e...
313  http://ufcstats.com/fighter-details/76ee3d666c...
314  http://ufcstats.com/fighter-details/4361245697...
315  http://ufcstats.com/fighter-details/87f0b37f15...

[543 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=c&page=all
hello this is after soup
        FIRST      LAST      NICKNAME  \
0         Yan    Cabral
1        Juan   Cabrera  Papi Juancho
2       Alvin    Cacdac
3        Alex   Caceres  Bruce Leeroy
4       Vince   Cachero   The Anomaly
..        ...       ...           ...
289       Pat    Curran    Paddy Mike
290      Will    Currie         Drago
291     Chris    Curtis    Action-Man
292       Ion  Cutelaba      The Hulk
293  Gleidson     Cutis         Poney

                                                   URL
0    http://ufcstats.com/fighter-details/7cdd3e5d3a...
1    http://ufcstats.com/fighter-details/601f8439a0...
2    http://ufcstats.com/fighter-details/ce7871949b...
3    http://ufcstats.com/fighter-details/7aa3d6964e...
4    http://ufcstats.com/fighter-details/ed2a8cc402...
..                                                 ...
289  http://ufcstats.com/fighter-details/d8291d0dd6...
290  http://ufcstats.com/fighter-details/b8ff02d570...
291  http://ufcstats.com/fighter-details/5442f1bc4b...
292  http://ufcstats.com/fighter-details/cd13728ae1...
293  http://ufcstats.com/fighter-details/44a94bbde4...

[294 rows x 4 columns]
        FIRST        LAST      NICKNAME  \
0         Tom       Aaron
1       Danny      Abbadi  The Assassin
2     Nariman     Abbasov     Bayraktar
3       David      Abbott          Tank
4       Hamdy  Abdelwahab    The Hammer
..        ...         ...           ...
289       Pat      Curran    Paddy Mike
290      Will      Currie         Drago
291     Chris      Curtis    Action-Man
292       Ion    Cutelaba      The Hulk
293  Gleidson       Cutis         Poney

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
289  http://ufcstats.com/fighter-details/d8291d0dd6...
290  http://ufcstats.com/fighter-details/b8ff02d570...
291  http://ufcstats.com/fighter-details/5442f1bc4b...
292  http://ufcstats.com/fighter-details/cd13728ae1...
293  http://ufcstats.com/fighter-details/44a94bbde4...

[837 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=d&page=all
hello this is after soup
        FIRST         LAST           NICKNAME  \
0       Sarah     D'alelio        The Monster
1      Marcos     da Matta        Parrumpinha
2    Henrique     da Silva       Frankenstein
3      Ariane     da Silva  Queen of Violence
4        Alex     Da Silva               Leko
..        ...          ...                ...
207     Merab  Dvalishvili        The Machine
208     David       Dvorak         Undertaker
209      Matt        Dwyer
210   Rolando           Dy      Dy Incredible
211  Shanelle         Dyer          Nightmare

                                                   URL
0    http://ufcstats.com/fighter-details/ac45450f75...
1    http://ufcstats.com/fighter-details/3b6d843435...
2    http://ufcstats.com/fighter-details/b0bd0c5425...
3    http://ufcstats.com/fighter-details/6551c64fbc...
4    http://ufcstats.com/fighter-details/c3ded6f715...
..                                                 ...
207  http://ufcstats.com/fighter-details/c03520b5c8...
208  http://ufcstats.com/fighter-details/9ada30894b...
209  http://ufcstats.com/fighter-details/8f0d576beb...
210  http://ufcstats.com/fighter-details/55ed59d541...
211  http://ufcstats.com/fighter-details/cfbb3edab7...

[212 rows x 4 columns]
        FIRST         LAST       NICKNAME  \
0         Tom        Aaron
1       Danny       Abbadi   The Assassin
2     Nariman      Abbasov      Bayraktar
3       David       Abbott           Tank
4       Hamdy   Abdelwahab     The Hammer
..        ...          ...            ...
207     Merab  Dvalishvili    The Machine
208     David       Dvorak     Undertaker
209      Matt        Dwyer
210   Rolando           Dy  Dy Incredible
211  Shanelle         Dyer      Nightmare

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
207  http://ufcstats.com/fighter-details/c03520b5c8...
208  http://ufcstats.com/fighter-details/9ada30894b...
209  http://ufcstats.com/fighter-details/8f0d576beb...
210  http://ufcstats.com/fighter-details/55ed59d541...
211  http://ufcstats.com/fighter-details/cfbb3edab7...

[1049 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=e&page=all
hello this is after soup
      FIRST      LAST           NICKNAME  \
0       Ben   Earwood
1      Cody      East  The Freight Train
2    Marvin   Eastman       The Beastman
3      Mike    Easton           The Hulk
4   Maurice     Eazel
..      ...       ...                ...
92    Andre     Ewell      Mr. Highlight
93    Chris     Ewert           El Tanke
94     Neal     Ewing
95   Manuel  Exposito
96  Jessica       Eye               Evil

                                                  URL
0   http://ufcstats.com/fighter-details/ee457ef1e1...
1   http://ufcstats.com/fighter-details/5713c1d2fa...
2   http://ufcstats.com/fighter-details/05866d8c3a...
3   http://ufcstats.com/fighter-details/bc7230f231...
4   http://ufcstats.com/fighter-details/4acb99524a...
..                                                ...
92  http://ufcstats.com/fighter-details/5f6f049d54...
93  http://ufcstats.com/fighter-details/54c2576b7f...
94  http://ufcstats.com/fighter-details/0798f55868...
95  http://ufcstats.com/fighter-details/a1cb266d7f...
96  http://ufcstats.com/fighter-details/f72465a784...

[97 rows x 4 columns]
      FIRST        LAST       NICKNAME  \
0       Tom       Aaron
1     Danny      Abbadi   The Assassin
2   Nariman     Abbasov      Bayraktar
3     David      Abbott           Tank
4     Hamdy  Abdelwahab     The Hammer
..      ...         ...            ...
92    Andre       Ewell  Mr. Highlight
93    Chris       Ewert       El Tanke
94     Neal       Ewing
95   Manuel    Exposito
96  Jessica         Eye           Evil

                                                  URL
0   http://ufcstats.com/fighter-details/93fe7332d1...
1   http://ufcstats.com/fighter-details/15df64c02b...
2   http://ufcstats.com/fighter-details/59a9d6dac6...
3   http://ufcstats.com/fighter-details/b361180739...
4   http://ufcstats.com/fighter-details/3329d692ae...
..                                                ...
92  http://ufcstats.com/fighter-details/5f6f049d54...
93  http://ufcstats.com/fighter-details/54c2576b7f...
94  http://ufcstats.com/fighter-details/0798f55868...
95  http://ufcstats.com/fighter-details/a1cb266d7f...
96  http://ufcstats.com/fighter-details/f72465a784...

[1146 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=f&page=all
hello this is after soup
         FIRST       LAST            NICKNAME  \
0       Edward  Faaloloto
1       Urijah      Faber  The California Kid
2      Melinda     Fabian
3      Wagnney    Fabiano        The Silencer
4      Bartosz   Fabinski         The Butcher
..         ...        ...                 ...
139     Travis     Fulton         The Ironman
140        Sam     Fulton
141  Masakatsu     Funaki
142    Ricardo      Funch          Golden Boy
143   Katsuaki     Furuki

                                                   URL
0    http://ufcstats.com/fighter-details/6224e8d0a3...
1    http://ufcstats.com/fighter-details/78114b7199...
2    http://ufcstats.com/fighter-details/8c02015677...
3    http://ufcstats.com/fighter-details/40389d39a9...
4    http://ufcstats.com/fighter-details/e17ac6410c...
..                                                 ...
139  http://ufcstats.com/fighter-details/911fb26546...
140  http://ufcstats.com/fighter-details/1f5f756585...
141  http://ufcstats.com/fighter-details/aa3153a994...
142  http://ufcstats.com/fighter-details/e9e1acc965...
143  http://ufcstats.com/fighter-details/c3e2eca94b...

[144 rows x 4 columns]
         FIRST        LAST      NICKNAME  \
0          Tom       Aaron
1        Danny      Abbadi  The Assassin
2      Nariman     Abbasov     Bayraktar
3        David      Abbott          Tank
4        Hamdy  Abdelwahab    The Hammer
..         ...         ...           ...
139     Travis      Fulton   The Ironman
140        Sam      Fulton
141  Masakatsu      Funaki
142    Ricardo       Funch    Golden Boy
143   Katsuaki      Furuki

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
139  http://ufcstats.com/fighter-details/911fb26546...
140  http://ufcstats.com/fighter-details/1f5f756585...
141  http://ufcstats.com/fighter-details/aa3153a994...
142  http://ufcstats.com/fighter-details/e9e1acc965...
143  http://ufcstats.com/fighter-details/c3e2eca94b...

[1290 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=g&page=all
hello this is after soup
         FIRST           LAST      NICKNAME  \
0        James         Gabert
1      Gustavo        Gabriel
2      Claudia        Gadelha     Claudinha
3    Alavutdin        Gadjiev
4      Magomed  Gadzhiyasulov
..         ...            ...           ...
228     Justin        Guthrie
229    Horacio      Gutierrez  The Punisher
230      Chris      Gutierrez      El Guapo
231      Mando      Gutierrez       El Toro
232       Mike         Guymon     The Joker

                                                   URL
0    http://ufcstats.com/fighter-details/fcd8b62389...
1    http://ufcstats.com/fighter-details/fe98f86284...
2    http://ufcstats.com/fighter-details/ec34349e7d...
3    http://ufcstats.com/fighter-details/a7a79b8efb...
4    http://ufcstats.com/fighter-details/6e344b7142...
..                                                 ...
228  http://ufcstats.com/fighter-details/a789defa90...
229  http://ufcstats.com/fighter-details/cd85b48dc8...
230  http://ufcstats.com/fighter-details/45f0cc9d18...
231  http://ufcstats.com/fighter-details/5f33ae0620...
232  http://ufcstats.com/fighter-details/eaea0fc7b7...

[233 rows x 4 columns]
       FIRST        LAST      NICKNAME  \
0        Tom       Aaron
1      Danny      Abbadi  The Assassin
2    Nariman     Abbasov     Bayraktar
3      David      Abbott          Tank
4      Hamdy  Abdelwahab    The Hammer
..       ...         ...           ...
228   Justin     Guthrie
229  Horacio   Gutierrez  The Punisher
230    Chris   Gutierrez      El Guapo
231    Mando   Gutierrez       El Toro
232     Mike      Guymon     The Joker

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
228  http://ufcstats.com/fighter-details/a789defa90...
229  http://ufcstats.com/fighter-details/cd85b48dc8...
230  http://ufcstats.com/fighter-details/45f0cc9d18...
231  http://ufcstats.com/fighter-details/5f33ae0620...
232  http://ufcstats.com/fighter-details/eaea0fc7b7...

[1523 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=h&page=all
hello this is after soup
       FIRST        LAST          NICKNAME  \
0    Chelsea     Hackett            Hammer
1      Keith     Hackney  The Giant Killer
2       Cody      Haddon
3       Jake      Hadley        White Kong
4      Steve      Hadsel
..       ...         ...               ...
222     Adam      Hunter         Warhammer
223      Joe      Hurley
224  Solomon  Hutcherson              King
225    Young       Hwang
226   In Soo       Hwang         Legendary

                                                   URL
0    http://ufcstats.com/fighter-details/184b7a36d5...
1    http://ufcstats.com/fighter-details/bf12aca029...
2    http://ufcstats.com/fighter-details/8e6654e9f0...
3    http://ufcstats.com/fighter-details/60a42bf824...
4    http://ufcstats.com/fighter-details/99793cf88c...
..                                                 ...
222  http://ufcstats.com/fighter-details/edc9eb3051...
223  http://ufcstats.com/fighter-details/21b54430c8...
224  http://ufcstats.com/fighter-details/155bfc7ed3...
225  http://ufcstats.com/fighter-details/8588d14c49...
226  http://ufcstats.com/fighter-details/1c01d98628...

[227 rows x 4 columns]
       FIRST        LAST      NICKNAME  \
0        Tom       Aaron
1      Danny      Abbadi  The Assassin
2    Nariman     Abbasov     Bayraktar
3      David      Abbott          Tank
4      Hamdy  Abdelwahab    The Hammer
..       ...         ...           ...
222     Adam      Hunter     Warhammer
223      Joe      Hurley
224  Solomon  Hutcherson          King
225    Young       Hwang
226   In Soo       Hwang     Legendary

                                                   URL
0    http://ufcstats.com/fighter-details/93fe7332d1...
1    http://ufcstats.com/fighter-details/15df64c02b...
2    http://ufcstats.com/fighter-details/59a9d6dac6...
3    http://ufcstats.com/fighter-details/b361180739...
4    http://ufcstats.com/fighter-details/3329d692ae...
..                                                 ...
222  http://ufcstats.com/fighter-details/edc9eb3051...
223  http://ufcstats.com/fighter-details/21b54430c8...
224  http://ufcstats.com/fighter-details/155bfc7ed3...
225  http://ufcstats.com/fighter-details/8588d14c49...
226  http://ufcstats.com/fighter-details/1c01d98628...

[1750 rows x 4 columns]
http://ufcstats.com/statistics/fighters?char=i&page=all
hello this is after soup
          FIRST         LAST              NICKNAME  \
0            Al     Iaquinta                Raging
1        Khadis    Ibragimov
2        Minoki     Ichihara
3         Alibi       Idiris
4           Dan          Ige                   50K
5        Valeri      Ignatov
6        Sergey      Ignatov
7       Fabiano          Iha
8        Seichi      Ikemoto
9       Mikhail    Iloukhine
10        Zelim      Imadaev
11       Yusuke      Imamura
12     Masakazu      Imanari
13  Nassourdine       Imavov            The Sniper
14         Brad         Imes  Hillbilly Heartthrob
15      Michael     Imperato
16          Rui        Imura
17        Chris       Indich
18        Chris        Inman
19         Guto     Inocente
20        Enson        Inoue       Yamato Damashii
21         Egan        Inoue
22      Katsuya        Inoue
23      Takeshi        Inoue                  Lion
24        Naoki        Inoue
25        Jorge    Interiano
26        Jason      Ireland     The Irish Tornado
27        James        Irvin           The Sandman

,FIRST,LAST,NICKNAME,URL
0,Tom,Aaron,,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny,Abbadi,The Assassin,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman,Abbasov,Bayraktar,http://ufcstats.com/fighter-details/59a9d6dac6...
3,David,Abbott,Tank,http://ufcstats.com/fighter-details/b361180739...
4,Hamdy,Abdelwahab,The Hammer,http://ufcstats.com/fighter-details/3329d692ae...
...,...,...,...,...
37,Alex,Zuniga,,http://ufcstats.com/fighter-details/02d808afb9...
38,George,Zuniga,,http://ufcstats.com/fighter-details/1291dd6b8a...
39,Allan,Zuniga,Tigre,http://ufcstats.com/fighter-details/523af801b3...
40,Brahyan,Zurcher,,http://ufcstats.com/fighter-details/392878af46...
41,Virgil,Zwicker,RezDog,http://ufcstats.com/fighter-details/0c277f3ff6...

In [32]:
# Add fighter id in ufc_fighter_details.csv
from pathlib import Path

csv_path = Path(config["fighter_details_file_name"])  # e.g., ../data/ufc_fighter_details.csv
df = pd.read_csv(csv_path)

df["FIGHTER_ID"] = (
    df["URL"].astype(str).str.strip().str.rstrip("/").str.split("/").str[-1]
)

cols = ["FIGHTER_ID"] + [c for c in df.columns if c != "FIGHTER_ID"]
df = df[cols]

df.to_csv(csv_path, index=False)

print(f"✅ Updated {csv_path} | rows: {len(df)}")
display(df.head(10))

✅ Updated ../data/ufc_fighter_details.csv | rows: 4423

,FIGHTER_ID,FIRST,LAST,NICKNAME,URL
0,93fe7332d16c6ad9,Tom,Aaron,NaN,http://ufcstats.com/fighter-details/93fe7332d1...
1,15df64c02b6b0fde,Danny,Abbadi,The Assassin,http://ufcstats.com/fighter-details/15df64c02b...
2,59a9d6dac61c2540,Nariman,Abbasov,Bayraktar,http://ufcstats.com/fighter-details/59a9d6dac6...
3,b361180739bed4b0,David,Abbott,Tank,http://ufcstats.com/fighter-details/b361180739...
4,3329d692aea4dc28,Hamdy,Abdelwahab,The Hammer,http://ufcstats.com/fighter-details/3329d692ae...
5,841695e02c99a521,Mansur,Abdul-Malik,NaN,http://ufcstats.com/fighter-details/841695e02c...
6,2f5cbecbbe18bac4,Shamil,Abdurakhimov,Abrek,http://ufcstats.com/fighter-details/2f5cbecbbe...
7,c0ed7b208197e8de,Hiroyuki,Abe,Abe Ani,http://ufcstats.com/fighter-details/c0ed7b2081...
8,5140122c3eecd307,Daichi,Abe,NaN,http://ufcstats.com/fighter-details/5140122c3e...
9,c9f6385af6df66d7,Papy,Abedi,Makambo,http://ufcstats.com/fighter-details/c9f6385af6...

# Parse Fighter Tale of the Tape

Includes:
<br>
Fighter
<br>
Height
<br>
Weight
<br>
Reach
<br>
Stance
<br>
DOB
<br>
URL

In [33]:
# define list of urls of fighters to parse
list_of_fighter_urls = list(all_fighter_details_df['URL'])

## Optional clean scrape
only run this if you want to clear out the existing tott csv file and start from scratch

In [ ]:
# File paths
tott_path = Path(config["fighter_tott_file_name"])
ckpt_path = Path("processed_fighter_tott.ckpt")

# Make sure folders exist
tott_path.parent.mkdir(parents=True, exist_ok=True)
tott_path.parent.mkdir(parents=True, exist_ok=True)

# Reset CSVs to header-only
pd.DataFrame(columns=config["fighter_tott_column_names"]).to_csv(tott_path, index=False)

# Remove checkpoint
ckpt_path.unlink(missing_ok=True)

print(f"✅ Cleared (header only): {tott_path}")
print(f"✅ Deleted checkpoint (if existed): {ckpt_path}")

✅ Cleared (header only): ../data/ufc_fighter_tott.csv
✅ Deleted checkpoint (if existed): processed_fighter_tott.ckpt

In [39]:
import time
from tqdm.notebook import tqdm as tqdm_notebook

# ---------- I/O paths ----------
tott_path = Path(config["fighter_tott_file_name"])                # e.g. ../data/ufc_fighter_tott.csv
ckpt_path = Path("processed_fighter_tott.ckpt")    # checkpoint file

# ---------- source URLs ----------
try:
    list_of_fighter_urls  # already defined elsewhere
    src_urls = list_of_fighter_urls
except NameError:
    # fallback: read from fighter details CSV
    details_path = Path(config["fighter_details_file_name"])
    df_urls = pd.read_csv(details_path, usecols=["URL"])
    src_urls = df_urls["URL"].dropna().astype(str).unique().tolist()

# ---------- checkpoint + already-scraped ----------
done = set()
if ckpt_path.exists():
    done.update(u.strip() for u in ckpt_path.read_text().splitlines() if u.strip())

# (Optional) also skip any URLs already present in output CSV
if tott_path.exists() and tott_path.stat().st_size > 0:
    try:
        out_urls = pd.read_csv(tott_path, usecols=["URL"], dtype=str)["URL"].dropna().unique().tolist()
        done.update(out_urls)
    except Exception:
        pass

# Build todo list
todo = [u for u in src_urls if u not in done]

# For a quick test, limit how many to process this run (0 = no limit)
LIMIT = 0  # e.g. set to 50 for a small batch
if LIMIT > 0:
    todo = todo[:LIMIT]

print(f"Total fighter URLs: {len(src_urls)} | already done: {len(done)} | to do now: {len(todo)}")

# ---------- helpers ----------
def append_csv(df: pd.DataFrame, path: Path, columns: list):
    """Append rows to CSV with consistent column order; write header if new."""
    if df is None or df.empty:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    write_header = (not path.exists()) or path.stat().st_size == 0
    df.reindex(columns=columns).to_csv(path, mode="a", header=write_header, index=False)

fail_log = []

# ---------- run ----------
pbar = tqdm_notebook(total=len(todo))
for url in todo:
    try:
        soup = LIB.get_soup(url)  # your (now) robust get_soup
        parsed = LIB.parse_fighter_tott(soup)
        one_df = LIB.organise_fighter_tott(parsed, config["fighter_tott_column_names"], url)

        # persist immediately
        append_csv(one_df, tott_path, config["fighter_tott_column_names"])

        # checkpoint after successful write
        with open(ckpt_path, "a") as f:
            f.write(url + "\n")

        # polite delay
        time.sleep(0.3)
    except Exception as e:
        print(f"⚠️ Failed {url} -> {e}")
        fail_log.append({"URL": url, "ERROR": str(e)})
        time.sleep(0.8)
    finally:
        pbar.update(1)
pbar.close()

# ---------- quick peek ----------
if tott_path.exists() and tott_path.stat().st_size > 0:
    peek = pd.read_csv(tott_path)
    print(f"✅ Current Tale-of-the-Tape rows: {len(peek)}")
    display(peek.tail(10))

Total fighter URLs: 4423 | already done: 359 | to do now: 4064

  0%|          | 0/4064 [00:00<?, ?it/s]

✅ Current Tale-of-the-Tape rows: 4423

,FIGHTER,HEIGHT,WEIGHT,REACH,STANCE,DOB,URL
4413,James Zikic,"6' 2""",205 lbs.,--,Orthodox,"Mar 01, 1977",http://ufcstats.com/fighter-details/4b4fc3ddc3...
4414,Errol Zimmerman,"6' 3""",185 lbs.,--,Orthodox,"Apr 20, 1986",http://ufcstats.com/fighter-details/0aa74d04c1...
4415,Cat Zingano,"5' 6""",145 lbs.,"68""",Southpaw,"Jul 01, 1982",http://ufcstats.com/fighter-details/3ecd936bd8...
4416,Igor Zinoviev,"6' 1""",199 lbs.,--,Orthodox,--,http://ufcstats.com/fighter-details/108afe61a2...
4417,Dave Zitanick,--,170 lbs.,--,NaN,"Mar 05, 1980",http://ufcstats.com/fighter-details/be124bdd60...
4418,Alex Zuniga,--,145 lbs.,--,NaN,--,http://ufcstats.com/fighter-details/02d808afb9...
4419,George Zuniga,"5' 9""",185 lbs.,--,NaN,--,http://ufcstats.com/fighter-details/1291dd6b8a...
4420,Allan Zuniga,"5' 7""",155 lbs.,"70""",Orthodox,"Apr 04, 1992",http://ufcstats.com/fighter-details/523af801b3...
4421,Brahyan Zurcher,--,145 lbs.,--,NaN,"Mar 10, 1996",http://ufcstats.com/fighter-details/392878af46...
4422,Virgil Zwicker,"6' 2""",205 lbs.,"74""",NaN,"Jun 26, 1982",http://ufcstats.com/fighter-details/0c277f3ff6...

In [40]:
# Path from your YAML config
tott_path = Path(config["fighter_tott_file_name"])  # e.g., ../data/ufc_fighter_tott.csv

# Load (as strings to avoid dtype issues)
df = pd.read_csv(tott_path, dtype=str)

# If a fight id column already exists with weird casing, normalize it first
for c in list(df.columns):
    if c.lower() == "fighter_id" and c != "FIGHTER_ID":
        df = df.rename(columns={c: "FIGHTER_ID"})
        break

# (Re)create FIGHTER_ID from the last segment of URL
df["FIGHTER_ID"] = (
    df["URL"].astype(str).str.strip().str.rstrip("/").str.split("/").str[-1]
)

# Reorder: FIGHTER_ID first
df = df[["FIGHTER_ID"] + [c for c in df.columns if c != "FIGHTER_ID"]]

# Save back
df.to_csv(tott_path, index=False)

print(f"✅ Added FIGHTER_ID to {tott_path} | rows: {len(df)}")
display(df.head(10))

✅ Added FIGHTER_ID to ../data/ufc_fighter_tott.csv | rows: 4423

,FIGHTER_ID,FIGHTER,HEIGHT,WEIGHT,REACH,STANCE,DOB,URL
0,93fe7332d16c6ad9,Tom Aaron,--,155 lbs.,--,NaN,"Jul 13, 1978",http://ufcstats.com/fighter-details/93fe7332d1...
1,15df64c02b6b0fde,Danny Abbadi,"5' 11""",155 lbs.,--,Orthodox,"Jul 03, 1983",http://ufcstats.com/fighter-details/15df64c02b...
2,59a9d6dac61c2540,Nariman Abbasov,"5' 8""",155 lbs.,"66""",Orthodox,"Feb 01, 1994",http://ufcstats.com/fighter-details/59a9d6dac6...
3,b361180739bed4b0,David Abbott,"6' 0""",265 lbs.,--,Switch,"Apr 26, 1965",http://ufcstats.com/fighter-details/b361180739...
4,3329d692aea4dc28,Hamdy Abdelwahab,"6' 2""",264 lbs.,"72""",Southpaw,"Jan 22, 1993",http://ufcstats.com/fighter-details/3329d692ae...
5,841695e02c99a521,Mansur Abdul-Malik,"6' 2""",185 lbs.,"80""",Orthodox,"Oct 07, 1997",http://ufcstats.com/fighter-details/841695e02c...
6,2f5cbecbbe18bac4,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",http://ufcstats.com/fighter-details/2f5cbecbbe...
7,c0ed7b208197e8de,Hiroyuki Abe,"5' 6""",145 lbs.,--,Orthodox,--,http://ufcstats.com/fighter-details/c0ed7b2081...
8,5140122c3eecd307,Daichi Abe,"5' 11""",170 lbs.,"71""",Orthodox,"Nov 27, 1991",http://ufcstats.com/fighter-details/5140122c3e...
9,c9f6385af6df66d7,Papy Abedi,"5' 11""",185 lbs.,--,Southpaw,"Jun 30, 1978",http://ufcstats.com/fighter-details/c9f6385af6...