In [1]:
'''
Overview
this notebook parses all past ufc fight stats when run, it does not include upcoming fights


scrape ufc fight stats
get all event details, name, url, date, location for all ufc events
for each event, get fight details all fights on card
parse each fight to get fight stats of both fighters
'''

'\nOverview\nthis notebook parses all past ufc fight stats when run, it does not include upcoming fights\n\n\nscrape ufc fight stats\nget all event details, name, url, date, location for all ufc events\nfor each event, get fight details all fights on card\nparse each fight to get fight stats of both fighters\n'

In [1]:
# imports
import pandas as pd
from tqdm.notebook import tqdm_notebook

# import library
import scrape_ufc_stats_library as LIB

# import config
import yaml
config = yaml.safe_load(open('scrape_ufc_stats_config.yaml'))

# Parse Event Details
Includes:
<br>
Event
<br>
URL
<br>
Date
<br>
Location
<br>

In [2]:
# define url to parse
events_url = config['completed_events_all_url']

In [3]:
# get soup
soup = LIB.get_soup(events_url)

# parse event details
all_event_details_df = LIB.parse_event_details(soup)

# show event details
display(all_event_details_df)

# write event details to file
all_event_details_df.to_csv(config['event_details_file_name'], index=False)

,EVENT,URL,DATE,LOCATION
0,UFC Fight Night: Dolidze vs. Hernandez,http://ufcstats.com/event-details/6cd3dfc54f01...,"August 09, 2025","Las Vegas, Nevada, USA"
1,UFC Fight Night: Taira vs. Park,http://ufcstats.com/event-details/f2c934689243...,"August 02, 2025","Las Vegas, Nevada, USA"
2,UFC Fight Night: Whittaker vs. De Ridder,http://ufcstats.com/event-details/28d8638ea0a7...,"July 26, 2025","Abu Dhabi, Abu Dhabi, United Arab Emirates"
3,UFC 318: Holloway vs. Poirier 3,http://ufcstats.com/event-details/b8e2f10efb6e...,"July 19, 2025","New Orleans, Louisiana, USA"
4,UFC Fight Night: Lewis vs. Teixeira,http://ufcstats.com/event-details/7b03d9df5910...,"July 12, 2025","Nashville, Tennessee, USA"
...,...,...,...,...
737,UFC 6: Clash of the Titans,http://ufcstats.com/event-details/1c3f5e85b59e...,"July 14, 1995","Casper, Wyoming, USA"
738,UFC 5: The Return of the Beast,http://ufcstats.com/event-details/dedc3bb440d0...,"April 07, 1995","Charlotte, North Carolina, USA"
739,UFC 4: Revenge of the Warriors,http://ufcstats.com/event-details/b60391da771d...,"December 16, 1994","Tulsa, Oklahoma, USA"
740,UFC 3: The American Dream,http://ufcstats.com/event-details/1a49e0670dfa...,"September 09, 1994","Charlotte, North Carolina, USA"
741,UFC 2: No Way Out,http://ufcstats.com/event-details/a6a9ab5a824e...,"March 11, 1994","Denver, Colorado, USA"

# Parse Fight Details
Includes:
<br>
Event
<br>
Bout
<br>
URL

In [4]:
# define list of urls of fights to parse
list_of_events_urls = list(all_event_details_df['URL'])

In [5]:
# create empty df to store fight details
all_fight_details_df = pd.DataFrame(columns=config['fight_details_column_names'])

# loop through each event and parse fight details
for url in tqdm_notebook(list_of_events_urls):

    # get soup
    soup = LIB.get_soup(url)

    # parse fight links
    fight_details_df = LIB.parse_fight_details(soup)
    
    # concat fight details
    all_fight_details_df = pd.concat([all_fight_details_df, fight_details_df])

# show all fight details
display(all_fight_details_df)

# write fight details to file
all_fight_details_df.to_csv(config['fight_details_file_name'], index=False)

  0%|          | 0/742 [00:00<?, ?it/s]

,EVENT,BOUT,URL
0,UFC Fight Night: Dolidze vs. Hernandez,win vs. Anthony Hernandez,http://ufcstats.com/fight-details/68fe62bac7fd...
1,UFC Fight Night: Dolidze vs. Hernandez,win vs. Steve Erceg,http://ufcstats.com/fight-details/37d58369782c...
2,UFC Fight Night: Dolidze vs. Hernandez,win vs. Iasmin Lucindo,http://ufcstats.com/fight-details/646c79a7ecd1...
3,UFC Fight Night: Dolidze vs. Hernandez,win vs. Andre Fili,http://ufcstats.com/fight-details/98d6771af9b0...
4,UFC Fight Night: Dolidze vs. Hernandez,win vs. Jean Matsumoto,http://ufcstats.com/fight-details/ed5383b50ffc...
...,...,...,...
10,UFC 2: No Way Out,win vs. Orlando Wiet,http://ufcstats.com/fight-details/3b020d4914b4...
11,UFC 2: No Way Out,win vs. Frank Hamaker,http://ufcstats.com/fight-details/d917c8c7461b...
12,UFC 2: No Way Out,win vs. Johnny Rhodes,http://ufcstats.com/fight-details/ccee020be2e8...
13,UFC 2: No Way Out,win vs. Patrick Smith,http://ufcstats.com/fight-details/4b9ae533ccb3...
14,UFC 2: No Way Out,win vs. Scott Morris,http://ufcstats.com/fight-details/4acab67848e7...

In [7]:
# This part is for normalizing the csv file by adding the id field

df = pd.read_csv(config['fight_details_file_name'])

df.insert(0, "EVENT_ID", df["URL"].str.strip().str.split("/").str[-1])
df.to_csv(config['fight_details_file_name'], index=False)

print(f"✅ {config['fight_details_file_name']} created successfully!")
df.head()

✅ ../data/ufc_fight_details.csv created successfully!

,EVENT_ID,EVENT,BOUT,URL
0,68fe62bac7fd8bb0,UFC Fight Night: Dolidze vs. Hernandez,win vs. Anthony Hernandez,http://ufcstats.com/fight-details/68fe62bac7fd...
1,37d58369782cb86b,UFC Fight Night: Dolidze vs. Hernandez,win vs. Steve Erceg,http://ufcstats.com/fight-details/37d58369782c...
2,646c79a7ecd12e5f,UFC Fight Night: Dolidze vs. Hernandez,win vs. Iasmin Lucindo,http://ufcstats.com/fight-details/646c79a7ecd1...
3,98d6771af9b0ebe5,UFC Fight Night: Dolidze vs. Hernandez,win vs. Andre Fili,http://ufcstats.com/fight-details/98d6771af9b0...
4,ed5383b50ffcdded,UFC Fight Night: Dolidze vs. Hernandez,win vs. Jean Matsumoto,http://ufcstats.com/fight-details/ed5383b50ffc...

# Parse Fight Results and Fight Stats

Fight Results Includes:
<br>
Event
<br>
Bout
<br>
Weightclass
<br>
Method
<br>
Round
<br>
Time
<br>
Time Format
<br>
Referee
<br>
Details
<br>

Fight Stats Includes:
<br>
Event
<br>
Bout
<br>
Round
<br>
Fighter
<br>
Kd
<br>
Sig.Str.
<br>
Sig.Str. %
<br>
Total Str.
<br>
Td
<br>
Td %
<br>
Sub.Att
<br>
Rev.
<br>
Ctrl
<br>
Head
<br>
Body
<br>
Leg
<br>
Distance
<br>
Clinch
<br>
Ground
<br>

In [7]:
# define list of urls of fights to parse
list_of_fight_details_urls = list(all_fight_details_df['URL'])

In [8]:
# create empty df to store fight results
all_fight_results_df = pd.DataFrame(columns=config['fight_results_column_names'])
# create empty df to store fight stats
all_fight_stats_df = pd.DataFrame(columns=config['fight_stats_column_names'])

# loop through each fight and parse fight results and stats
for url in tqdm_notebook(list_of_fight_details_urls):

    # get soup
    soup = LIB.get_soup(url)

    # parse fight results and fight stats
    fight_results_df, fight_stats_df = LIB.parse_organise_fight_results_and_stats(
        soup,
        url,
        config['fight_results_column_names'],
        config['totals_column_names'],
        config['significant_strikes_column_names']
        )

    # concat fight results
    all_fight_results_df = pd.concat([all_fight_results_df, fight_results_df])
    # concat fight stats
    all_fight_stats_df = pd.concat([all_fight_stats_df, fight_stats_df])

# show all fight results
display(all_fight_results_df)
# show all fight stats
display(all_fight_stats_df)

# write to file
all_fight_results_df.to_csv(config['fight_results_file_name'], index=False)
# write to file
all_fight_stats_df.to_csv(config['fight_stats_file_name'], index=False)

  0%|          | 0/8300 [00:00<?, ?it/s]

KeyboardInterrupt: